### ISSUE TITLE
Private Games / Room#

### ISSUE THREAD

**Issue by simon-kyger** [simon-kyger/brawlhallacrewbattles#14]
Need to have the games clickable to join for public game.

Need to have join game button transferred into join private game, which then creates a modal specifying two inputs, room num and password.

**Comment by simon-kyger** [comment]
First part I finished, yeakoo can you finish second part please.

**Comment by simon-kyger** [comment]
Update package.json when this is finished with new version number.

**Comment by yeakoo** [comment]
Done! Also, we'll be using room# as password for private lobbies
